### PR TITLE
Fix determiner and collector should not be filtered by discipline

### PR DESCRIPTION
**Pull request by caalle**
Fixed an issue with determiner and collector being filtered by discipline. This will cause no agent to appear if you have a collection selected.

### CODE REVIEW

**Comment by caalle** [comment]
To test checkout branch and use beta server as host and try to search for Determiner or Collector with a Collection selected.

**Comment by Johnny70** [comment]
Tested and confirmed.

**Comment by caalle** [comment]
Waiting for @Inkimar

**Comment by Inkimar** [comment]
tested and it works :+1:

**Comment by caalle** [comment]
@Johnny70 you can go ahead and merge this. Don't forget to add a release note before updating the beta server though.

**Pull request closed without merging**
